version: '2'
services:
  mailhog:
      image: mailhog/mailhog
      container_name: mailhog
      ports:
       - "1025:1025"
       - "8025:8025"
     environment: 
       - MH_STORAGE=maildir
       - MH_MAILDIR_PATH=/tmp/mailhog
     volumes:
       - ./maildir:/tmp/mailhog
