version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit
    volumes:
      - ./db:/data
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    hostname: localhost
    ports:
      - "15672:15672"
      - "5672:5672"
