version: '2'
services:
  mysql:
      image: mysql
      environment:
        - MYSQL_ROOT_PASSWORD=gu123451
      ports:
        - 3306:3306
      volumes:
        - ./db:/var/lib/mysql
        - ./db/initscript:/docker-entrypoint-initdb.d
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
